#!/usr/bin/env bash
sudo -v


repo=core
arch=x86_64
count=$(grep -o "Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/${repo}/os/${arch}" /etc/pacman.d/mirrorlist | wc -l)

if [ "$count" -eq 0 ]; then
    sudo sed -i '1i\Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist
fi

if ! pacman -Q git base-devel go zsh &> /dev/null; then
    echo "start to install git base-devel go..."
    sudo pacman -S --noconfirm --needed git base-devel go zsh
else
    echo "git base-devel go already config, skipping..."
fi

echo "start to config yay"
export GOPROXY=https://goproxy.io,direct
export GOPRIVATE=git.mycompany.com,github.com/my/private

if [[ ! -d "$HOME/yay" ]]; then
    git clone https://aur.archlinux.org/yay.git ~/yay
fi
cd "$HOME/yay" && 
makepkg -si

if [ $? -ne 0 ]; then
    echo "pacman install git base-devel fail, error code: $?"
    exit 1 
fi

# use archlinuxcn
mirror_line="\n[archlinuxcn]\nServer = https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/\$arch"
if ! grep -q "archlinuxcn" /etc/pacman.conf; then
    echo -e "$mirror_line" | sudo tee -a /etc/pacman.conf
else
    echo "archlinuxcn mirrors already config, skipping..."
fi

sudo pacman -Syu

sudo pacman-key --recv-keys "farseerfc@archlinux.org"
sudo pacman-key --lsign-key "farseerfc@archlinux.org"

if ! pacman -Q archlinuxcn-keyring &> /dev/null; then
    echo "start to install archlinuxcn-keyring ..."
    sudo pacman -S --noconfirm --needed archlinuxcn-keyring
else
    echo "archlinuxcn-keyring already config, skipping..."
fi

sudo pacman -Syu

config_dir="$HOME/.config"
# fonts_dir="$config_dir/fonts"
# link_dir="$config_dir/link"

chsh -s "$(which zsh)"

if [ ! -f "$HOME/.bashrc" ]; then
  rm -rf "$HOME/.bashrc"
  rm -rf "$HOME/.bash_profile"
  rm -rf "$HOME/.bash_history"
fi

echo "link config file"
shopt -s dotglob
for file in "$config_dir/link"/*; do
  if [ -f "$file" ]; then
    filename=$(basename "$file")
    ln -s -f "$file" "$HOME/$filename"
    echo "Created symlink: $HOME/$filename -> $file"
  fi
done
shopt -u dotglob
echo "link done"

git config --global user.name "jacjdk"
git config --global user.email "inpaz@proton.me"
git config --global core.editor "nvim"
git config --global credential.helper store
git config --global core.excludesFile $HOME/.gitignore
git config --global init.defaultBranch 'main'

yay -Syu
yay -S - < "$config_dir"/pkglist.txt --noconfirm --needed

RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup rustup install stable

git clone https://github.com/tmux-plugins/tpm ~/.local/share/tmux
